### ISSUE TITLE
[PyASL] Roadmap

### ISSUE THREAD

**Issue by dreamwhite** [dreamwhite/bugtracker#31]
Current roadmap of needed functions to implement in the project

- [x] Parse `DefinitionBlock` content
- [x] Parse `External` references
- [x] Create scopes using nested dicts/lists inside a global tree named `tree` or something like that
    - e.g. `_SB.PCI0.LPCB` will be translated onto `tree['_SB']['PCI0']['LPCB']`
    - [ ] Check if names with less than 4 chars may get wrongly translated
        - e.g. `_SB` may get translated in `_SB_`

**Comment by dreamwhite** [comment]
Reminder for the future me (prob 4 hours more or less). Given that the parser will check each line, when you get a `Scope (...)` like line, use

```python
scope_name = current_line.split()[1][1:-1]
scope_name.split('.') # this will split the path in a single list with multiple elements, the first one is the parent, while the others are the child
```

**Comment by dreamwhite** [comment]
Alright, I have some serious issues with my mind. Scope recognition works but when it comes to talk about nested devices, it fucks up.

Need some investigation ffs

**Comment by dreamwhite** [comment]
I'm kinda bored about this project and don't see any valid reason to exist. I'll close this issue, but if anyone wants to mess up with the code, feel free to submit a PR!
